---
title: "Aim 1 EDA"
author: "Andrew Mertens"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}
source(here::here("0-config.R"))
library(DataExplorer)
library(SmartEDA)
```

## Mapsan


```{r}
d <-readRDS(paste0(dropboxDir,"Data/cleaned_ipd_env_data.rds"))
d <- d %>% subset(., select = c(dataid, study,sample, target, round, pos, logquant))

ms <- d %>% filter(study=="mapsan")

res <- ms %>% group_by(sample, target) %>%
  summarize(N=n(), npos=sum(pos), prev=round(mean(pos),3)*100, mean_log_quant=round(mean(logquant, na.rm=T),2)) %>%
  as.data.frame()

knitr::kable(res)

```


## WBK

```{r}
wbk <- d %>% filter(study=="WBK")

res <- wbk %>% group_by(sample, target) %>%
  filter(!is.na(sample)) %>%
  summarize(N=n(), npos=sum(pos), prev=round(mean(pos),3)*100, mean_log_quant=round(mean(logquant, na.rm=T),2)) %>%
  as.data.frame()

knitr::kable(res)

```

## WBB

```{r}
wbb <- d %>% filter(study=="WBB")
res <- wbb %>% group_by(round, sample, target) %>%
  filter(!is.na(sample)) %>%
  summarize(N=n(), npos=sum(pos), prev=round(mean(pos),3)*100, mean_log_quant=round(mean(logquant, na.rm=T),2)) %>%
  as.data.frame()

knitr::kable(res)

```


## Gram Vikas


