---
title: "WASH IPD figure and tables"
author: "Andrew Mertens"
date: "1/3/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn = -1) 
library(janitor)
library(knitr)
library(here)
library(table1)
library(rvest)

source(here("0-config.R"))


op = function(x, d=2) sprintf(paste0("%1.",d,"f"), x) 
 library(pander)
panderOptions('digits', 2)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('graph.fontsize', 8)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

#resRR <- readRDS(file=here("results/pooled_RR.Rds"))

load(here("figures/all_tables.Rdata"))
load(here("figures/agg_tables.Rdata"))
load(here("figures/abundance_tables.Rdata"))
load(here("figures/all_figures.Rdata"))
load(here("figures/density_figures.Rdata"))
load(here("figures/outcome_groups.Rdata"))

#load(here("figures/abundance_table_ROQ.Rdata"))
abund_ROQ <- read.csv(here("figures/abundance_table_ROQ.csv"))
abund_ROQ <-abund_ROQ %>% subset(., select= c(-X))

```


<!-- ## List of pathogen/MST outcomes by group -->

<!-- ```{r, echo=T, warning=F, message=F} -->
<!-- any_pathogens  -->
<!--      any_virus -->
<!--      any_bacteria -->
<!--      any_protozoa  -->
<!--      general_MST  -->
<!--      animal_MST  -->
<!--      human_MST  -->
<!--      any_MST  -->
<!-- ``` -->



## Table 1. Prevalence of pathogens by sample type tested in each study

```{r, echo=F, warning=F, message=F}
knitr::kable(target_presence_long_P)

```

## Table 2. Prevalence of microbial source tracking markers by sample type tested in each study

```{r, echo=F, warning=F, message=F}
knitr::kable(target_presence_long_MST)

```


## Primary figures


```{r, echo=F, warning=F, message=F, fig.width = 10, fig.height = 5}

p_1

```
