---
title: "Supplimentary Material: Effect of water, sanitation and hygiene interventions on enteropathogen detection in the environment: an individual participant data meta-analysis"
author: "Andrew Mertens, Jack Colford, Oliver Cumming, Joe Brown, Jill Stewart, David Holcomb, Jackie Knee, Tom Clasen, Heather Reese, Amy Pickering, Clair Null, Steve Luby, Jessica Grembi, Ben Arnold, Audrie Lin, Jade Benjamin-Chung, Laura Kwong, Lauren Steinbaum, Ali Boehm, Kara Nelson, Erica Fuhrmeister, Mahbubur Rahman, Sammy Njenga, Rassul Nala, Ruwan Thilakaratne, Ayse Ercumen (middle order not finalized)"
#output: redoc::redoc
output: 
  officedown::rdocx_document:
      reference_docx: "manuscript_format.docx"
header-includes:
  - \setlength{\parindent}{4em}
  - \setlength{\parskip}{0em}
indent: true
bibliography: WASH-IPD.bib
bib-humanities: FALSE
csl: nature.csl

---


We developed a search strategy with a two-step process. First, we examined known studies meeting our inclusion criteria for keywords and Medical Subject Heading (MeSH) terms relating to WASH interventions, microbial source tracking, environmental contamination, enteric infection; diarrhea, and child growth. Next, we performed an initial search using these terms and extracted other relevant terms and synonyms from the search results. Search terms are listed in Supplementary Table S1. 


We used the compound (group of households with shared sanitation) as the independent unit in non-cluster-randomized studies and the specified unit of clustering in cluster-randomized trials.

We used the original study's imputation strategy if available and otherwise imputed values ourselves. 


Holcomb et al. 2020 measured human (Bacteroides and M. smithii) and avian (GFD) MST targets in `r FP %>% ungroup() %>% distinct(sampleid) %>% summarise(N=n()) %>% as.numeric()` food samples , but there were no samples positive for GFD, 2 samples positive for M. smithii, and 7 samples positive for Bacteroides so we did not estimate prevalence ratios for MST markers in food samples for this study nor include these markers in the aggregate variables.


 Of samples with any pathogen detected, 98.4% detected at least one non-zoonotic pathogen, while 63.9% detected at least one zoonotic pathogen. Confidence intervals for prevalence ratios for zoonotic pathogens were therefore wider but the point estimates were similar for zoonotic vs. non-zoonotic pathogens.