
source(paste0(here::here(),"/src/3-aim2/2-analysis/1-combine-health-datasets.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/2-aim-2-clean-covariates.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/3-aim-2-analysis.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/3-aim-2-abundance-analysis.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/3-aim-2-analysis-all-diarrhea.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/3-aim-2-pathogen-specific-analysis.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/3-aim-2-analysis-tmle2.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/4-aim-2-subgroup-analysis.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/4-aim-2-subgroup-analysis-age.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/4-pool-results-aim2.R"))
source(paste0(here::here(),"/src/3-aim2/2-analysis/9-compile-tmle.R"))
